---
- import_tasks: "system.yml"
- debug:
    msg: "Searching for OS Platform for package install"

- import_tasks: "ubuntu-install.yml"
  when: 
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution'] == "Debian"

- import_tasks: "osx-install.yml" 
  when: 
    - ansible_facts['os_family'] == "Darwin"
- import_tasks: "packages.yml"
- import_tasks: "docker.yml"
- import_tasks: "wallpaper.yml"

- name: ALL DONE
  ansible.builtin.debug:
    msg: 
    - "PLAYBOOK FINISHED"
    - "exit and re-enter terminal to test aliases"
