---
- name: Remove apt lock file
  file:
    state: absent
    path: "{{ item  }}"
  with_items:
    - "/var/lib/dpkg/lock"
  become: true 

- name: Install Debian/Ubuntu packages
  package: 
    name: "{{ item }}"  
  with_items:
    - "{{ apt_pkg_list }}"
  tags: apt
  register: result
  until: result is not failed
  retries: 5
  delay: 5
  become: true

# Install Gnome Extensions
- name: GNOME | Install GNOME related packages
  package: 
    name: "{{ item }}"  
  with_items:
    - "{{ gnome_pkg_list }}"
  tags: apt
  register: result
  until: result is not failed
  retries: 5
  delay: 5
  become: true 

- name: Remove useless packages from the cache
  shell:
    cmd: "apt autoclean"
  become: true

- name: Run apt get update
  shell: 
    cmd: "apt update"
  become: true 
